sudo: required

language: java

services:
  - docker

before_install:
  - wget http://mirrors.ae-online.de/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar xf apache-maven-3.3.9-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH

install: /bin/true

script:
  - mvn -fae clean install

cache:
  directories:
    - $HOME/.m2

